services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  generator:
    build: ./generator
    depends_on:
      - rabbitmq

  processor:
    build: ./processor
    depends_on:
      - rabbitmq

  reporter:
    build: ./reporter
    depends_on:
      - rabbitmq
